[package]
name = "ndi-screen-share"
version = "0.1.0"
edition = "2024"

[dependencies]
ndi = { git = "https://github.com/maxjoehnk/ndi-rs", branch = "feature/ndi-5" }
color-eyre = "0.6"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(target_os = "macos")'.dependencies]
scap = "0.1.0-beta.1"

[target.'cfg(target_os = "windows")'.dependencies]
scap = "0.1.0-beta.1"

[target.'cfg(target_os = "linux")'.dependencies]
scap = "0.0.8"
